### ISSUE TITLE
"Still at home location" after leaving

### ISSUE THREAD

**Issue by eelton** [rmceoin/cominghome#14]
I've had issues with away not triggering when I leave the house.  Today, I see in my history that "Geofence left home" at 7:12 AM, but at 7:14 AM it says "Still at home location."  I did not return home (I was driving to work, 11 miles away).

![screenshot_20161005-183135](https://cloud.githubusercontent.com/assets/22649069/19135764/c92ce908-8b2c-11e6-892d-fc18da79135f.png)

**Comment by rmceoin** [comment]
The "Still at home location" is what is put into History if either the geo location is within the home radius or the home Wi-Fi SSID is detected after a certain amount of time after the initial "Geofence left home" trigger.  The app is fully dependent upon what the phone tells it, which is fully the function of the Android OS. 

What I've found is the geo aspect of the phones to be somewhat sketchy.  Thus why I tried to add a degree of checking and double-checking.

Unfortunately I have not been maintaining the app since January, in part because Nest refused to grant my app a full license since their developer guidelines unnecessarily _require_ that apps ask every single time before changing the away/home status.  You're not allowed to change it in the background.  Ironically a month after denying my request they updated their app to do the very same thing. /shrug

I've been using the Nest app solely for auto-away based on the phone's presence at home.   It's not perfect, but hopefully they'll continue to improve it.

**Comment by eelton** [comment]
Thanks for the reply.  I have the SSID thing turned off--I'd rather have false away than false home events.

I've tried using the Nest app, but it seemed to trigger auto away only about half the time.  It's unfortunate they've made things difficult for you--I had been using your app since you first released it, and it had worked well for me until recently.
